name: "All tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: "Lint and core tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build
      - run: yarn lint
      # - run: yarn test-with-coverage && yarn report-coverage
      - run: yarn test262
  test-older-node:
    name: "Test on older node versions"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # We support down to node 8, but mocha requires node 14.
          - node_version: '14'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: yarn
      - run: yarn build
      - run: yarn test-only
